const express = require("express");
const app = express();
const port = 3500;
const router = require("./routes/routes");
const connect = require("./config/dbconfig");
connect(port, app);
app.set("view engine", "ejs");
app.use(express.static("public"));
app.use(express.urlencoded({ extended: true }));
app.use("/", router);